// Code generated by go2go; DO NOT EDIT.


//line arrayOperations.go2:1
package go2

//line arrayOperations.go2:1
import (
//line arrayOperations.go2:1
 "fmt"
//line arrayOperations.go2:1
 "testing"
//line arrayOperations.go2:1
)

//line arrayOperations.go2:1
type Importable୦ int

//line arrayOperations.go2:1
var _ = fmt.Errorf
//line arrayOperations.go2:1
var _ = testing.AllocsPerRun
